version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: apogeeze_dev
      POSTGRES_HOST_AUTH_METHOD: trust
